// Fetch Spec
//
// This file contains a set of fetch related commands and their expected
// results. Fetch is one of the most frequently used commands in IMAP,
// and is also one of the most complex.
//
// Many of these examples are pulled directly from the IMAP specification.
import {
	CRLF,
	// Helper FNs
	atom,
	litString,
	op,
	num,
	// Premade tokens
	tokenCRLF,
	tokenSP,
	tokenStar,
	tokenOpenParen,
	tokenCloseParen,
	qString,
	tokenNil,
} from "./constants";
import { TestSpec } from "./types";

// And finally, build our set of test specs
const fetchSet: TestSpec[] = [
	{
		name: "Untagged FETCH with non-body literal",
		input: [
			"* 12 FETCH (INTERNALDATE {26}",
			CRLF,
			"17-Jul-1996 02:44:25 -0700)",
			CRLF,
		].join(""),
		results: {
			lexer: [
				tokenStar,
				tokenSP,
				num(12),
				tokenSP,
				atom("FETCH"),
				tokenSP,
				op("("),
				atom("INTERNALDATE"),
				tokenSP,
				litString("17-Jul-1996 02:44:25 -0700"),
				op(")"),
				tokenCRLF,
			],
			parser: {
				content: {
					sequenceNumber: 12,
					date: new Date("17-Jul-1996 02:44:25 -0700"),
				},
				type: "FETCH",
			},
		},
	},
	{
		name: "Untagged FETCH (flags, date, size, envelope, body[structure])",
		input: [
			"* 12 FETCH (FLAGS (\\Seen)",
			' INTERNALDATE "17-Jul-1996 02:44:25 -0700"',
			" RFC822.SIZE 4286",
			' ENVELOPE ("Wed, 17 Jul 1996 02:23:25 -0700 (PDT)"',
			' "IMAP4rev1 WG mtg summary and minutes"',
			' (("Terry Gray" NIL "gray" "cac.washington.edu"))',
			' (("Terry Gray" NIL "gray" "cac.washington.edu"))',
			' (("Terry Gray" NIL "gray" "cac.washington.edu"))',
			' ((NIL NIL "imap" "cac.washington.edu"))',
			' ((NIL NIL "minutes" "CNRI.Reston.VA.US")',
			'("John Klensin" NIL "KLENSIN" "MIT.EDU")) NIL NIL',
			' "<B27397-0100000@cac.washington.edu>")',
			//' BODY ("TEXT" "PLAIN" ("CHARSET" "US-ASCII") NIL NIL "7BIT" 3028',
			")", //" 92))",
			CRLF,
		].join(""),
		results: {
			lexer: [
				tokenStar,
				tokenSP,
				num(12),
				tokenSP,
				atom("FETCH"),
				tokenSP,
				tokenOpenParen,
				atom("FLAGS"),
				tokenSP,
				tokenOpenParen,
				op("\\"),
				atom("Seen"),
				tokenCloseParen,
				tokenSP,
				atom("INTERNALDATE"),
				tokenSP,
				qString("17-Jul-1996 02:44:25 -0700"),
				tokenSP,
				atom("RFC822.SIZE"),
				tokenSP,
				num(4286),
				tokenSP,
				atom("ENVELOPE"),
				tokenSP,
				tokenOpenParen,
				qString("Wed, 17 Jul 1996 02:23:25 -0700 (PDT)"),
				tokenSP,
				qString("IMAP4rev1 WG mtg summary and minutes"),
				tokenSP,
				tokenOpenParen,
				tokenOpenParen,
				qString("Terry Gray"),
				tokenSP,
				tokenNil,
				tokenSP,
				qString("gray"),
				tokenSP,
				qString("cac.washington.edu"),
				tokenCloseParen,
				tokenCloseParen,
				tokenSP,
				tokenOpenParen,
				tokenOpenParen,
				qString("Terry Gray"),
				tokenSP,
				tokenNil,
				tokenSP,
				qString("gray"),
				tokenSP,
				qString("cac.washington.edu"),
				tokenCloseParen,
				tokenCloseParen,
				tokenSP,
				tokenOpenParen,
				tokenOpenParen,
				qString("Terry Gray"),
				tokenSP,
				tokenNil,
				tokenSP,
				qString("gray"),
				tokenSP,
				qString("cac.washington.edu"),
				tokenCloseParen,
				tokenCloseParen,
				tokenSP,
				tokenOpenParen,
				tokenOpenParen,
				tokenNil,
				tokenSP,
				tokenNil,
				tokenSP,
				qString("imap"),
				tokenSP,
				qString("cac.washington.edu"),
				tokenCloseParen,
				tokenCloseParen,
				tokenSP,
				tokenOpenParen,
				tokenOpenParen,
				tokenNil,
				tokenSP,
				tokenNil,
				tokenSP,
				qString("minutes"),
				tokenSP,
				qString("CNRI.Reston.VA.US"),
				tokenCloseParen,
				tokenOpenParen,
				qString("John Klensin"),
				tokenSP,
				tokenNil,
				tokenSP,
				qString("KLENSIN"),
				tokenSP,
				qString("MIT.EDU"),
				tokenCloseParen,
				tokenCloseParen,
				tokenSP,
				tokenNil,
				tokenSP,
				tokenNil,
				tokenSP,
				qString("<B27397-0100000@cac.washington.edu>"),
				tokenCloseParen,
				tokenCloseParen,
				tokenCRLF,
			],
			parser: {
				content: {
					date: new Date("1996-07-17T09:44:25.000Z"),
					envelope: {
						bcc: { list: [] },
						cc: {
							list: [
								{
									route: null,
									name: null,
									mailbox: "minutes",
									host: "CNRI.Reston.VA.US",
								},
								{
									route: null,
									name: "John Klensin",
									mailbox: "KLENSIN",
									host: "MIT.EDU",
								},
							],
						},
						date: "Wed, 17 Jul 1996 02:23:25 -0700 (PDT)",
						from: {
							list: [
								{
									name: "Terry Gray",
									mailbox: "gray",
									host: "cac.washington.edu",
									route: null,
								},
							],
						},
						inReplyTo: null,
						messageId: "<B27397-0100000@cac.washington.edu>",
						replyTo: {
							list: [
								{
									host: "cac.washington.edu",
									mailbox: "gray",
									name: "Terry Gray",
									route: null,
								},
							],
						},
						sender: {
							list: [
								{
									host: "cac.washington.edu",
									mailbox: "gray",
									name: "Terry Gray",
									route: null,
								},
							],
						},
						subject: "IMAP4rev1 WG mtg summary and minutes",
						to: {
							list: [
								{
									host: "cac.washington.edu",
									mailbox: "imap",
									name: null,
									route: null,
								},
							],
						},
					},
					flags: {
						flagMap: new Map([
							[
								"\\Seen",
								{
									isKnownName: true,
									isWildcard: false,
									name: "\\Seen",
								},
							],
						]),
						hasWildcard: false,
					},
					sequenceNumber: 12,
					size: 4286,
				},
				type: "FETCH",
			},
		},
	},
];

export default fetchSet;
